# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_1_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_2_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_3_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_4_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_5_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_6_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_7_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_8_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 9  -max_iteration 30

# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 1  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 2  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 3  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 4  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 5  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 6  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 7  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 8  -max_iteration 30
# python3  AttackSetRe.py   -i /home/ubuntu/hbl/CIFAR10/StatsRes/classwise_data/class_9_seed.npy  -o GA_output/GA_100_logits_cifar_resnet/100_50  -pop_num 100  -subtotal 50  -type mnist -model /home/ubuntu/hbl/CIFAR10/StatsRes/models/resnet50_cifar10.pth  -target 0  -max_iteration 30
# python3 AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet5_mnist.h5  -target 2  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 3  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 4  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 5  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 6  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 7  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 8  -max_iteration 30
# python AttackSet.py   -i ./seeds/mnist/seed_v1/class_1_seed.npy  -o GA_output/GA_100_logits_mnist_lenet4/100_50  -pop_num 100  -subtotal 50  -type mnist -model profile/lenet4_mnist.h5  -target 9  -max_iteration 30
